### ISSUE TITLE
Snippets for dynamic tags in Stata 15 [Feature Request]

### ISSUE THREAD

**Issue by pjpaulpj** [zizhongyan/StataImproved#6] opened 2017-08-04 06:48 UTC
Hi,

First, thanks for the great piece of code that you have developed. Makes coding in Stata a lot easier.

This is more of a feature request than an issue. Stata 15 has finally introduced support for Markdown syntax in Stata via the `dyntext` [package](http://www.stata.com/manuals/pdyntext.pdf#pdyntext). Stata's markups feature a lot of tags (similar to code chunk options in R-markdown) that control the output of the code as it appears in the converted PDF or HTML document. It would be great if you could code in snippet support for the tags to make scripting easier.

Regards,

**Comment by zizhongyan** [comment] 2017-08-04 11:58
Hi PJ Paul,

I have just installed a trial version of Stata 15 today. According to my understanding, to use the stata 15 markdown, one needs to code the script in a plain text file first, and then use dyntext/markdown command to convert it. 

My preliminary idea is to add a series of "dd_xxx" snippets. What do you think?


More specifically, we could add:

dd_v for:
<<dd_version: ... >>

dd_dis for:
<<dd_display: %4.2f `....'>>


dd_do for:
<<dd_do>>
....
<</dd_do>>


dd_ignore for:
<<dd_ignore>>
....
<</dd_ignore>>





Best regards,
Zizhong

**Comment by pjpaulpj** [comment] 2017-08-04 12:02
Makes sense. 
We should also add a snippet for the `~~~~` delimiters.

Regards,

**Comment by zizhongyan** [comment] 2017-08-04 12:27
Thanks.
I see. 
But the problem is the syntax highlighting in the txt file. Users might not want the txt file has a Stata style syntax highlighting.

**Comment by pjpaulpj** [comment] 2017-08-04 12:34
Does this [workaround](https://superuser.com/questions/622456/set-current-language-without-saving-file-in-sublime-text) solve that?

**Comment by zizhongyan** [comment] 2017-08-04 15:19
Sure, this does work. 

I added the snippets for stata markdown in this file:
https://github.com/zizhongyan/StataImproved/blob/master/markdown.sublime-completions

please feel free to change/add if you wish. Then I will put a new release later if these are fine with you.

The scheme of syntax highlighting is also changed accordingly. 

Thank you for the great suggestion!

**Comment by pjpaulpj** [comment] 2017-08-06 02:10
Thanks for the great edits.

My only comment would be about the `dd_tilde`. Currently the completion for `dd_tilde` is to output _one_ set of delimiter tildes (ie ~~~~). However, codeblocks in Stata markdown always require a _pair_ of tildes. Perhaps, it makes sense then, to make `dd_tilde` output a pair of delimiter tildes, rather than just one set. 

I've made a pull request to this effect.

Regards,

**Comment by zizhongyan** [comment] 2017-08-11 14:43
Hi,

Sorry for the delayed response as I was a bit busy this week.

Many thanks for the pull request. I have merged your suggestion.

Btw, do you think we could simply use "~~~~" to trigger the snippet? It seems in ST3, the special character "~" cannot be used as a starting character for completion trigger..

Best wishes,

**Closed** 2017-08-11 15:03 UTC
